const String homeScreen = '/';
const String walletAndCard = 'Wallet & Card';
const String wallet = 'Wallet';
const String lifelineCardWallet = 'Lifeline Card Wallet';
const String holdWallet = 'Hold Wallet';
const String lifelineCoin = 'Lifeline Coin';
const String cashBackCoin = 'CashBack Coin';
const String card = 'Card';
const String addCashBackCoin = 'Add CashBack Coin';
